export enum CodeError {
  IS_REGISTERED = 1000,
  NOT_FOUND = 1001,
  INVALID_NUMBER = 1002,
  NOT_EMPTY = 1003,
  IS_DESABLE = 1004,
  IS_BLOCKED = 1005,
  CANNOT_BE_CHANGED = 1006,
  INCORRECT_FIRST_ACCESS_PASSWORD = 1101,
  INCORRECT_PASSWORD_EMAIL = 1111,
  NEW_PASSWORD_CANNOT_MATCH = 1102,
  PASSWORD_CONFIRMATION_NOT_MATCH = 1103,
  IS_NUMBER = 1201,
  IS_STRING = 1202,
  NO_SPACE = 1203,
  NO_SPECIAL_CHARACTER = 1204,
  IS_EMAIL = 1205,
  SPECIAL_CHARACTER = 1206,
  MIN_ONE_NUMBER = 1207,
  MIN_CHARACTER = 1208,
  MAX_CHARACTER = 1209,
  DIFERENT_OF_ZERO = 1210,
  IS_NOT_BOOLEAN = 1211,
  BLANK_SPACES_BEGINNING = 2424,
  INVALID_DATA_RANGER = 3000,
  IN_PROCESS = 4000,
  REENVIADO = 5000,
  NOT_ALLOWED_RESTRICTED_TRANSACTIONS_ONLY = 6000,
  MAX_ONE_TRANSACTION_FOR_RESOURCE = 6001,
  NOT_ALLOWED = 6002,
  NOT_ALLOWED_SAME_TRANSACTIONS = 6003,
  IS_PIPE_CODE = 7000,
  IS_MACHINE_IP = 8000,
  EXTERNAL_LOGIN_ERROR = 9000,
}

export enum PathName {
  'home' = 'Home',
  'user-management' = 'Gestão de Usuários',
  'dashboard' = 'Dashboard',
  'report' = 'Relatório',
  'profiles' = 'Controle de Acesso',
  'production' = 'Cadastro de Produção',
  'process' = 'Execução de Meta',
  'goal' = 'Planejamento de Metas',
  'productivity' = 'Produtividade',
  'machine-monitoring' = 'Monitoramento de Máquina',
}

export enum Situation {
  'Programado' = 1,
  'Em andamento' = 2,
  'Vencido' = 3,
  'Atrasado' = 4,
  'Incompleto' = 5,
  'Concluído' = 6,
}

export enum FormatInputType {
  MACHINE_NAME = 'machine_name',
  MACHINE_IP = 'machine_ip',
  PIPE_CODE = 'pipe_code',
  PIPE_NAME = 'pipe_name',
  PIPE_LENGTH = 'pipe_length',
  PIPE_DIAMETER = 'pipe_diameter',
  PIPE_BENDS = 'pipe_bends',
  PRODUCTION_GOAL_ORDER = 'production_goal_order',
  PROFILE_NAME = 'profile_name',
  USER_NAME = 'user_name',
  USER_EMAIL = 'user_email',
  PRODUCTION_GOAL_EXPECTED = 'production_goal_expected',
  DAILY_PRODUCTION_GOAL = 'daily_production_goal',
  PIPE_BOTTOM = 'pipe_model_bottom_margin',
  PIPE_TOP = 'pipe_model_top_margin',
  PIPE_REFERENCE = 'pipe_model_reference',
}

export enum FileTypesEnum {
  '.pdf' = 'application/pdf',
  '.xlsx' = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}
